### PR TITLE
Edit MeetingLink validation regex and LinkAdd tests

### LINKED ISSUE #157: [PE-D] Link validation
When an invalid link is added, this message shows:
```
The URL must start with either http:// or https://, followed by a subdomain, and end with top level domains like .com or .org
```
However, this link validation is not entirely enforced. A link that does not follow the format of having a subdomain and top level domain is still considered valid. Consider either revising the link validation regex, or rephrase this message to reflect the actual behaviour. The part of the UG that mentions this should also be reviewed.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: yongping827/ped#4

### LINKED ISSUE #170: [PE-D] Link add
Details: Links with invalid TLDs accepted

Steps:

linkadd 16  l/https://hi.sacs.a

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: leeweiminsg/ped#12

### LINKED ISSUE #185: [PE-D] Linkadd without top level domain
-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Wincenttjoi/ped#12

### LINKED ISSUE #198: [PE-D] linkadd allows invalid command to pass
linkadd prompt says link must end with .com or .org, but invalid inputs pass through

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: aqcd/ped#7

### PR DESCRIPTION
**Pull request by JoeyToh**

### CODE REVIEW

**Review by siqiang-ng — APPROVED** [review]
LGTM

**Review by siqiang-ng — COMMENTED** [review]
Do you want to explain what is the expected format in MESSAGE_USAGE? or did u?

**Review by akgrenSoar — APPROVED** [review]
LGTM

**Comment by akgrenSoar** [comment]
If im not wrong, the error message does not inform user about syntax of linkadd.
e.g. `linkadd 1` does not tell user that they must specify `l/` tag

**Review by akgrenSoar — CHANGES_REQUESTED** [review]
If im not wrong, the error message does not inform user about syntax of linkadd.
e.g. `linkadd 1` does not tell user that they must specify `l/` tag
please check. thanks

**Review by akgrenSoar — APPROVED** [review]

**Pull request merged**
