### PR TITLE
Add tag list command

### LINKED ISSUE #48: As an user, I can list all the tags in the tag list
so that I can quickly find all the tags that I have added.

### PR DESCRIPTION
**Pull request by siqiang-ng**
**Logic:** 
- Add TagListCommand class
- Add a parameter to CommandResult checking isTagList() (To be removed in v1.3)
- Change MainWindow.java to showTagList() if isTagList() but commandText.equals("list") is left intact
- Add TagListCommand to ProjactParser.java

**UI:**
- Change app title name to 'Projact App' instead of 'Address App'

**Test:**
- Add the TagList boolean field in CommandResultTest.java
- Created TagListCommandTest.java class

### CODE REVIEW

**Comment by akgrenSoar** [comment]
LGTM.

Minor nitpicks:
- Perhaps lowercase might be better than camelcase for command name (i.e. `taglist` instead of `tagList`)
- Test coverage can be improved for
  - java/seedu/address/logic/parser/ProjactParser.java
  - java/seedu/address/logic/commands/CommandResult.java

**Comment by siqiang-ng** [comment]
Thanks! Made the necessary edits. Let me check what I can do about CommandResult.java

**Comment by siqiang-ng** [comment]
Does anyone know how to generate the Code Coverage result again?

**Comment by akgrenSoar** [comment]
the codecov report automatically updates itself. It is showing the codecov for the latest commit already

**Review by JoeyToh — APPROVED** [review]
Looks good to merge

**Pull request merged**
