### PR TITLE
Fix contact list back to person list #42

### LINKED ISSUE #42: Fix Contact in UserGuide.md back to Person

### PR DESCRIPTION
**Pull request by siqiang-ng**
Fixes #42

### CODE REVIEW

**Review by yeo-kexin — COMMENTED** [review]
looks good to me

**Comment by akgrenSoar** [comment]
LGTM

**Review by JoeyToh — COMMENTED** [review]
Ok. Can merge.

**Comment by khinkhinn** [comment]
LGTM

**Review by khinkhinn — APPROVED** [review]

**Pull request merged**
